---
profile: ambient
pilot:
  env:
    PILOT_ENABLE_ALPHA_GATEWAY_API: true
    ISTIO_DUAL_STACK: "true"
  ipFamilyPolicy: RequireDualStack
meshConfig:
  defaultConfig:
    proxyMetadata:
      ISTIO_DUAL_STACK: "true"
  extensionProviders:
    - name: 'authelia'
      envoyExtAuthzHttp:
        service: 'authelia.authelia.svc.polycule.raft.lutris.house'
        port: 80
        pathPrefix: '/api/authz/ext-authz/'
        includeRequestHeadersInCheck:
          - accept
          - cookie
          - location
          - authorization
          - proxy-authorization
        headersToUpstreamOnAllow:
          - 'remote-*'
          - 'authelia-*'
        includeAdditionalHeadersInCheck:
          X-Forwarded-Proto: '%REQ(:SCHEME)%'
        headersToDownstreamOnDeny:
          - 'set-cookie'
        headersToDownstreamOnAllow:
          - 'set-cookie'
