---
apiVersion: v1
kind: Secret
metadata:
  name: lldap-credentials
  namespace: authelia
type: Opaque
stringData:
  smtp-password: '{{ smtp-password }}'
  storage-key: '{{ storage-key }}'
  oidc-jwks-key: '{{ oidc-jwks-key }}'
