---
apiVersion: v1
kind: Secret
metadata:
  name: lldap-credentials
  namespace: authelia
type: Opaque
stringData:
  authelia-password: '{{ authelia-password }}'
  sysadmin-password: '{{ sysadmin-password }}'
  jwt-secret: '{{ jwt-secret }}'
  key-seed: '{{ key-seed }}'
  admin-password: '{{ admin-password }}'
