gateways:
  - name: pihole
    hostnames:
      - pihole.raft.lutris.house
    listeners:
      - name: https
        port: 443
        protocol: HTTPS
        routes:
          - name: pihole
            service: pihole-web
            port: 80
            hostnames: []
