---
controllers:
  main:
    containers:
      main:
        env:
          OG_EXTERNAL_URL: https://gist.raft.lutris.house
          OG_OIDC_DISCOVERY_URL: https://auth.raft.lutris.house/.well-known/openid-configuration
          OG_OIDC_GROUP_CLAIM_NAME: groups
          OG_OIDC_ADMIN_GROUP: cluster_admin
persistence:
  opengist:
    enabled: true
    storageClass: nfs-ssd-csi
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 20Gi
