---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: pihole-exp
spec:
  encryptedData:
    password: AgB4WOkdyg7SsaCbw0VJz4xIsMpGOwU9Idi0Wt2KJiqzgcI56OcPFnBHpzx9+KPRz5A4Kw/bAK25EP88LuV1j8JIskiT1g/WA7c8I8xu4WaXxKIU24KZWEVcbWetZKIO7V1SrhuhvXxcyIoLzDB7J6NyoEfaP50cqxnIosUdGzo6ApbtAWuC7+LDhbbzYfLpzjYOYxEuhk3/kCBUdn4m6PQHW8u15E4PvRqBgSPGEc8kWh8rsoPyRPBwWkgUhjdIXK/fzJIuuygKLUbVQZROPKEuaLPHUK1egUdVO4MucSRr1EqeN7PKPqYMKM9bSl0pS8SusJTJF3aVgzwNFORz2N+lrOOVLcF0s7qcStWRRlISXB2eQuk7RJiv/xl0sHBrKxh+e+obSv+E3jRTx+EWWZj09appvi1SVGTnHvXgPEB3fSdxLXQp5678BdvVbC1Z/Q8io1o1MAFZAzvdWEyV5IpHUGQPgjtqQ8skKDgDlH/oVPD0qlPcuL+Pqou1ZM4X6S2RPpfkobaYYH0ciKkNlmIMNDUL4wrab4hf1QrJlziOFhUvGuoXeuS3HGmvzS8ep5mmSEjtFUzgBFt+/rgDl2zxYNrBLNAKldVOMrLaY7AY0LDJ77HDeVE5z6e73hflxjR/7ZY+T4UkqdNHMiOKzlj4bPycnJ+gNs07A+j7VAeFsv9R9o8kc2e++TghBwq6sbSU5dliwTYh+6LvkdRT
  template:
    metadata:
      name: pihole-admin
      namespace: pihole-exp
    type: Opaque
