---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cnpg.alerts
  namespace: monitoring
spec:
  groups:
    - name: cn-postgres
      rules:
        - record: cnpg_expected_replicas
          expr: sum by (label_cnpg_io_cluster, instance)
            (kube_pod_labels{label_cnpg_io_instance_role="replica"})
