---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ups.alerts
  namespace: monitoring
spec:
  groups:
    - name: ups.alerts
      rules:
        - alert: UPSLoadHigh
          annotations:
            description: 'UPS {{ $labels.ups }} on {{ $labels.instance }} is at {{ printf "%f" $value }}% load'
            summary: UPS {{ $labels.ups }} is at {{ printf "%f" $value }}% load
          expr: network_ups_tools_ups_load > 80
          for: 0m
          labels:
            severity: warning

        - alert: UPSLoadVeryHigh
          annotations:
            description: 'UPS {{ $labels.ups }} on {{ $labels.instance }} is at {{ printf "%f" $value }}% load'
            summary: UPS {{ $labels.ups }} is at {{ printf "%f" $value }}% load
          expr: network_ups_tools_ups_load > 90
          for: 0m
          labels:
            severity: critical

        - alert: UPSLineVoltageOutOfSpec
          annotations:
            description: 'Line in voltage for UPS {{ $labels.ups }} on {{ $labels.instance }} is out of range.  Input is at {{ printf "%d" $value }}V and range is 100V to 125V'
            summary: UPS {{ $labels.ups }} is at {{ printf "%d" $value }}V
          expr: (network_ups_tools_input_voltage > 125 or network_ups_tools_input_voltage < 100)
          for: 0m
          labels:
            severity: critical

        - alert: UPSBatteryLow
          annotations:
            description: 'Battery level for UPS {{ $labels.ups }} on {{ $labels.instance }} is low at {{ printf "%d" $value }}%'
            summary: UPS {{ $labels.ups }} battery is low at {{ printf "%d" $value }}%
          expr: network_ups_tools_battery_charge < 25
          for: 0m
          labels:
            severity: warning

        - alert: UPSBatteryVeryLow
          annotations:
            description: 'Battery level for UPS {{ $labels.ups }} on {{ $labels.instance }} is critically low at {{ printf "%d" $value }}%'
            summary: UPS {{ $labels.ups }} battery is low at {{ printf "%d" $value }}%
          expr: network_ups_tools_battery_charge < 15
          for: 0m
          labels:
            severity: critical

        - alert: UPSStatusUnknown
          annotations:
            description: 'UPS {{ $labels.ups }} on {{ $labels.instance }} has an unknown status'
            summary: 'UPS {{ $labels.ups }} status unknown'
          expr: network_ups_tools_ups_status{flag=~".+"} == 0
          for: 1m
          labels:
            severity: critical

        - alert: UPSStatusOnBattery
          annotations:
            description: 'UPS {{ $labels.ups }} on {{ $labels.instance }} is on battery'
            summary: 'UPS {{ $labels.ups }} is on battery'
          expr: network_ups_tools_ups_status{flag="OB"} == 1 or network_ups_tools_ups_status{flag="DISCHRG"} == 1
          for: 1m
          labels:
            severity: critical

        - alert: UPSStatusOffline
          annotations:
            description: 'UPS {{ $labels.ups }} on {{ $labels.instance }} is offline'
            summary: 'UPS {{ $labels.ups }} is offline'
          expr: network_ups_tools_ups_status{flag="OL"} == 0 or network_ups_tools_ups_status{flag="OFF"} == 1
          for: 1m
          labels:
            severity: critical

        - alert: UPSStatusOverload
          annotations:
            description: 'UPS {{ $labels.ups }} on {{ $labels.instance }} is overloaded'
            summary: 'UPS {{ $labels.ups }} is overloaded'
          expr: network_ups_tools_ups_status{flag="OVER"} == 1
          for: 0m
          labels:
            severity: critical
