---
name: ArgoCD Diff and Dry Run
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'

jobs:
  argocd-diff:
    runs-on: ubuntu-latest
    container:
      image: python:3.14-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Tools (ArgoCD CLI & yq)
        run: |
          mkdir -p $HOME/.local/bin

          # Download and install ArgoCD CLI locally
          curl -sSL -o $HOME/.local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x $HOME/.local/bin/argocd

          # Download and install yq locally
          wget -qO $HOME/.local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x $HOME/.local/bin/yq

          apt-get update
          apt-get install -y jq

          python3 -m pip install --upgrade pip
          pip3 install requests pyyaml

          # Expose this directory to the PATH for all subsequent steps in this job
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run ArgoCD Diff
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          REF_NAME: ${{ github.head_ref || github.ref_name || github.sha }}
        run: |
          echo "Starting ArgoCD diff process..."

          set +e

          OUTPUT_DIR="artifacts"
          mkdir -p $OUTPUT_DIR

          TEST_REPO=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}

          echo "Working on git ref: '${REF_NAME}'"

          ARGOCD_ERROR=0

          APP_NAME=applications-raft
          echo ""
          echo "Checking $APP_NAME"
          echo ""
          argocd app get $APP_NAME --refresh \
            --auth-token "$ARGOCD_TOKEN" \
            --server "$ARGOCD_SERVER" > /dev/null 2> $OUTPUT_DIR/"${APP_NAME}_refresh.stderr"

          REV_FLAGS="--source-positions 1 --revisions ${REF_NAME}"

          argocd app diff "$APP_NAME" ${REV_FLAGS} \
            --server "$ARGOCD_SERVER" \
            --auth-token "$ARGOCD_TOKEN" \
            --server-side-generate  > ${OUTPUT_DIR}/"${APP_NAME}.diff" 2> ${OUTPUT_DIR}/"${APP_NAME}_diff.stderr"

          ERROR_CODE=$?

          if [ $ERROR_CODE -eq 1 ]; then
            echo "diff found in $APP_NAME"

            cat ${OUTPUT_DIR}/"${APP_NAME}.diff"

            argocd app sync "$APP_NAME" ${REV_FLAGS} \
              --server "$ARGOCD_SERVER" \
              --auth-token "$ARGOCD_TOKEN" \
              --server-side --dry-run  > ${OUTPUT_DIR}/"${APP_NAME}.sync" 2>&1
          elif [ $ERROR_CODE -gt 1 ]; then
            echo "ERROR: argocd cli was unable to diff exit code $ERROR_CODE"
            echo ""
            echo "stdout:"
            cat ${OUTPUT_DIR}/"${APP_NAME}.diff"
            echo ""
            echo "stderr:"
            cat ${OUTPUT_DIR}/"${APP_NAME}_diff.stderr"
            ARGOCD_ERROR=$ERROR_CODE
          fi

          for app_file in argocd/applications/*.yaml; do
            [ -e "$app_file" ] || continue

            APP_NAME=$(yq e '.metadata.name' "$app_file")

            echo ""
            echo "Checking $APP_NAME in $app_file"
            echo ""

            argocd app get $APP_NAME --refresh \
                --auth-token "$ARGOCD_TOKEN" \
                --server "$ARGOCD_SERVER" > /dev/null 2> $OUTPUT_DIR/"${APP_NAME}_refresh.stderr"

            ERROR_CODE=$?
            if [ $ERROR_CODE -ne 0 ]; then
              echo "ERROR: argocd cli was unable to refresh"
              ARGOCD_ERROR=$ERROR_CODE
              continue
            fi

            HAS_SOURCES=$(yq eval '.spec.sources | select(. != null)' "$app_file")
            if [ -z "$HAS_SOURCES" ]; then
              # when i get time i should figure out what to do if i don't use sources
              continue
            fi

            SOURCES_COUNT=$(yq eval '.spec.sources | length' "$app_file")
            REV_FLAGS=""

            for ((i=0; i < SOURCES_COUNT; i++)); do
              POSITION=$((i + 1))

              REPO_URL=$(yq eval ".spec.sources[$i].repoURL" "$app_file")

              if [ "$REPO_URL" == "$TEST_REPO" ]; then
                REV_FLAGS="${REV_FLAGS} --source-positions ${POSITION} --revisions ${REF_NAME}"
              fi

            done

            argocd app diff "$APP_NAME" ${REV_FLAGS} \
              --server "$ARGOCD_SERVER" \
              --auth-token "$ARGOCD_TOKEN" \
              --server-side-generate  > ${OUTPUT_DIR}/"${APP_NAME}.diff" 2> ${OUTPUT_DIR}/"${APP_NAME}_diff.stderr"

            ERROR_CODE=$?

            if [ $ERROR_CODE -eq 1 ]; then
              echo "diff found in $APP_NAME"

              cat ${OUTPUT_DIR}/"${APP_NAME}.diff"

              argocd app sync "$APP_NAME" ${REV_FLAGS} \
                --server "$ARGOCD_SERVER" \
                --auth-token "$ARGOCD_TOKEN" \
                --server-side --dry-run  > ${OUTPUT_DIR}/"${APP_NAME}.sync" 2>&1
            elif [ $ERROR_CODE -gt 1 ]; then
              echo "ERROR: argocd cli was unable to diff exit code $ERROR_CODE"
              echo ""
              echo "stdout:"
              cat ${OUTPUT_DIR}/"${APP_NAME}.diff"
              echo ""
              echo "stderr:"
              cat ${OUTPUT_DIR}/"${APP_NAME}_diff.stderr"
              ARGOCD_ERROR=$ERROR_CODE
              continue
            fi

            echo ""
          done

          find "$OUTPUT_DIR" -type f -empty -delete
          exit $ARGOCD_ERROR

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: argocd-application-diffs
          path: artifacts/

      - name: Add diff to comment
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_URL: ${{ github.api_url }}
          REPO: ${{ github.repository }}
          COMMIT_SHA: ${{ github.sha }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          DIFFS=""
          CODE_BLOCK='```'
          CR=$(echo -e "\n")

          set +e
          ARTIFACTS="$(ls artifacts/*.diff)"
          if [ -z "$ARTIFACTS" ]; then
            DIFFS="No diffs found."
          else
            for f in artifacts/*.diff; do
              FILE_CONTENTS=$(cat $f)
              DIFFS="${DIFFS}${CR}${CODE_BLOCK}diff${CR}${FILE_CONTENTS}${CR}${CODE_BLOCK}"
            done
          fi
          set -e
          set -x

          if [ -z "${DIFFS}" ]; then
            DIFFS="No diffs found."
          fi

          REPORT_BODY="Argocd diff report:${CR}${DIFFS}"

          JSON_BODY="$(jq -n --arg body "${REPORT_BODY}" '{body: $body}')"
          echo "$JSON_BODY"

          if [ "$EVENT_NAME" == "pull_request" ]; then
            curl -X POST "$API_URL/repos/$REPO/issues/$PR_NUMBER/comments" \
              -H "Authorization: token $AUTH_TOKEN" \
              -H "Content-Type: application/json" \
              -d "$JSON_BODY"
          else
            curl -X POST "$API_URL/repos/$REPO/statuses/$COMMIT_SHA/comments" \
              -H "Authorization: token $AUTH_TOKEN" \
              -H "Content-Type: application/json" \
              -d "$JSON_BODY"
          fi
