---
name: ArgoCD Diff and Dry Run
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'

jobs:
  argocd-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Tools (ArgoCD CLI & yq)
        run: |
          mkdir -p $HOME/.local/bin

          # Download and install ArgoCD CLI locally
          curl -sSL -o $HOME/.local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x $HOME/.local/bin/argocd

          apt-get update
          apt-get install -y python3 python3-yaml python3-requests

          # Expose this directory to the PATH for all subsequent steps in this job
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run ArgoCD Diff
        env:
          API_URL: ${{ github.api_url }}
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          ARTIFACT_DIR: "artifacts"
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ github.sha }}
          EVENT_NAME: ${{ github.event_name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REF_NAME: ${{ github.head_ref || github.ref_name || github.sha }}
          REPO: ${{ github.repository }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
        run: |
          python3 .forgejo/scripts/argocd-differ.py

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: argocd-application-diffs
          path: artifacts/
