---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-sessions-key
  namespace: authelia
spec:
  encryptedData:
    password: AgBpxi4q4m9gklp464kQFrZEGuPp21MyiCCADEPKRMn4QNAE2ldGv1VLjsMdD+8A/cnsiOo2VwiE4z4T8Mptf6kbIif3NTo4wX30sbnluok5untWyRBuhwmzDpeONBZ6zkN4i8oBh//e1XtFUpzBnBWdfcejTj+G+1oZ/nHUj/DQmEx0WA3V+K9fsbYg7Rx/eQ2NyY75v0E3BhMIi/8qQ6yaOkMME0vwMLB6NXYeZmIdG8Mk9BBKlwH62vGzi48qWIn7B40L+UI67J1c5LNmI9ACgIL43qxHTaWQWjalefqQeEB5hGNLYtLMx5hNTMS+9jCEfHDC3xMw+Vk7wszRR5fKWSAqUKqq7xt1Y1tunRuW2eaX7JR53pdfYgN9i2D20v9H275RR8B6Q/QMoTl+9jnEDWOrOIrdqU9ippIB2MI2KSSjgQ9FBB7/loUs1339zc9QNpj7aNWuN7zMaYH8PeGxlOkIiQywcN1u/SrsdtQSt/kGpOC/PUHVtAjciSNZUNaJquHEVd6N3Z8yg4L5AKMmgBK3dm2ST4FNyAQGwrdsZL98DOGCgoz33uA8yOvBC9zM171JliUVf8D0KsaMQWDCeiEiOltVAd8jT9fFHW8T/pSL/WT/uFt4JKltDAQq2R5qNmW8Q7iN69mvRUd8kplqcPlCM2CeI6+WjlIxIsc1Y7xoTXKLh+TUZiq+All0H8irjmw6k5T2n/HcD7DtnxysXwuoascHpwNQINWhr0dbMtaK0tAWLAkSEb1rqcfsk87EnY/kh+VJAWI/tkFlRT2v
  template:
    metadata:
      name: authelia-sessions-key
      namespace: authelia
    type: Opaque
