---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-sessions-key
  namespace: authelia
spec:
  encryptedData:
    password: AgCBCtjFcFnbqXr+e/eSHzq5HQ/c68RUUyn4J86QWg2vuyWSja8PXa4bYYGeTuD6uYJutzrHk6CGhdJgzTynFGqQgCc9tsirAxdoD1J3kMhZkKzw8NV6nXDq76vOQlv6C9CfONhHyyySy58M/Qhqbvp5p5Bvn0CV2ilJ9POMsytmho/Pw7Du+VTTEqF6mwbCSGKCLrDZQFdlUD5wOBjm0QZly1ZMX+Rbpn0Ogp4SnbnaY6hm0AYJHo943gCKJLsFKLF49iD7fui1rwnZ3DRFDQaFbSVfZlBc075VvGvGfmrWuc/shurhvDK0qmo4h3BLZHzPgYpsYwjln5Q5B4i2qw/yuqXWYylhN8jQvXaZdpaGbcz4MII1ELnhcfQeZi7q3KSaRSkH7w+V/Md5Ry/GneHD8a1IoFK9g/ZhoEM7S4WuRif0hykHfsAwnP/XA3SGl9u0WvUUuDHn6REgdLJ0/1B3WuGN+Y3x7ofYR6BhOyQcPUcVgUiA4uzEyjwEDoWeuLToyAdhddTp42VswjvGRoeysb+2131xcPpdJA96UQc/WNqQnlHgSgr8QMEZQEu3kuz9xRw+jCeDqUblKI3zYV+5kTWX/dvG50HkP6ECAUjiV1FIKk4h59X1/EwXyNDxstf/nKerWb6MAiq7OdVKTYJAwqpT3dW91EQEWOADrq8LC0Ay1h2VWK0KK5rLVJrhaBkoNWDr3h4HJhkohvnP8VRlzq18P09QaweMq8FPOpu1TiNvvCudionLqrkL+PDJAkzHNGJMgMooe6mLBEwtXCXN
  template:
    metadata:
      name: authelia-sessions-key
      namespace: authelia
    type: Opaque
