---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-sessions-password
  namespace: authelia
spec:
  encryptedData:
    password: AgA4OKKfienVoQvzZqmIhbZ880EcBEfeo2gA4ps2K+LVLLcO+rPhsSLg2aJTcyxhZyp2NwRBv7/hZTljsgVeX7BgB8ztf1XOQV+PtbReAEZJ3rkoNokCcXcVOsbHnG7GhPqx7C0S2te3kI9SyRzTdfW7EURrwc9a0xPvPr4FV2IVz0L1BHXa4gpNkfY/peqUy2KsrE9S3FXKWtWSSZwqOe+yLaMhhKArEhn7dcjotDexhre62LYnwT1HCdwzUl6tjo6Wtu8u8pwUnfBhiMQA+QJ2UnRiL2Npfve8Zj37AlJooXJRHEYkihZAg25nhqhdK5vpxbUsN1G02G2B/usw964t8+0l2qBt71irNAUQAsBaxzFe1J0e8Az49bio6vW3+2TdrIYQgs+nAK3FZu9ZvEaMBLMjE7LS82XQqGw/g31DeSnN8evfqARt4P8R3JobiGMDpH+qRsq8h4obkI4/R7XERFxGJydOuJhNXcp3o2md0F6lLRTgxBlBXiKcN3iJVjgmfZqcvUgqpPHO3+1d2bp4/F5pJYLRSZz5Wujzi5To0GYifCxwtzUKXlFX/kCYPJMw4xhZCNOJ1I77nDnBZw/gIsYS1q8owor+vuI9088438qXstm8oaT8eG0wh3k1NmtH7+PNck/vOC2bVRPV9envDXPQMdYRY8z8G9VIC6JstQcjbg70Hi0FX7ZdOD6COd1mIngASdKxNADs54rMRL/zoeESsTgFz9pnMirPhEKag2lT2kirPyTAAZcXtfQPXS9A+0W9wvOWlaY343jz2k8N
  template:
    metadata:
      name: authelia-sessions-password
      namespace: authelia
    type: Opaque
