---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: authelia-storage
  namespace: authelia
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: authelia-storage
  podMetricsEndpoints:
    - port: metrics
