---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-sessions-password
  namespace: authelia
spec:
  encryptedData:
    password: AgAvqKlhJYHMYdeyWrBkErna6ed7YcejwucaA+a7ANgY/+Mn8NiDY4/OThwJIsqxTCygu+zaiXuw7PjdeNXIiKMxBzg9524+ywn2GAc+OgmTHYFHax25JykyjBH7KxCJT9ww2UVfQ4+rOkMj51ellYtPCxMN2QBdy8PHMNiv6OdtpIdMTMuqCFDM2513nyvDRbhokKBZ67U02KzvqreSqzzO6UQ2H3IT3NrUYaQpe2iRqkdx7iwJ6FMxLIEZqyRGABh0/RI19/nr8DuvCcEHkxA8gxATlBgNx6tHTYNEDtwFipOO5Zwe+5Lg9QZF2p9V0AQe8MajBp31PqVZvYKfAAz7GspTrbG5h9UhCPmYYH9kOVzPbF/LxSPh/3wVDS3pAps/kbCsGidzGOt9P1R5KvpS0ObPgZ8q3XblJXopcMOQJP3yV2nslRa8ZMLbqw8wvt5LAhgt19JzPKYZdS0IHJzfd3tQn1vViWhvTWtYdxBKCAzvnRSyMhtThcFfyCeEThKXJXXA6XJ+kya3UFm0tatbIwOPVzzj2JW/SQl0kOOuZDaRIZuIvch3vs+9ScDdyTYMe0uFLjHvcPVjKKx5ArKeGDa0vWH50jUiplM0HgMqNDRXKJO+WmjL9R8GkeG92Ys7bJmWylCinJL9YTX2qQ4DhVNQyIzbPLwHmaNIbrvsASd3ZMVK5xUERrkwH5zo9tikNueE8hfMhrdQsOS700NqaLbFabviWg91pHWCAvKJsZ68NTYLcAOgdPG3KMGSV0qHvF+e2vS9DHQauq2NVSbC
  template:
    metadata:
      name: authelia-sessions-password
      namespace: authelia
    type: Opaque
