---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-sessions-key
  namespace: authelia
spec:
  encryptedData:
    password: AgB+C4mVaDwyJm3qNY55i6E+tNMq+MSMchgev0iZr3ygFmeFFx6WSG0SsajauI2X3+qn8685fMtOyfzrDvWlx/BqyxVBuUhGJ/gxuWi9+Aj1cylPZKNi6+KYnDuTYmwLog4bEDwosy8D7A3ImvWm9RSh16M493SKhwwNX9/sA8S8WzaJxwp/qH2/4qUb2oGWPFX9wofaw3QDJe32spGPEkCs7+tOJij9QV8iqsdlswV0tTRijGOD+jQchUrr8Jw0Qz7bxhcaxhJvoIlJEjw+Uw1VffuanBWWuoCtinGJGBaz8g56uKRhstFIw1GfV1ZDYe/83gH/tW7wBuuqEpSPS+kjjfT51uih+1Uwm7H2yaJTGf/KmmXzkTiiHwwIfSqP7RtUAH3ScV0hihCcFTMBmOk+RkURcp4O23b0y7uV66MezYYsd7YWhaWpDgsJFStEJAGvq0+UWUrlmB1GFUjNfdPaZwUQ77IKj/rzZJqcQqOpdNGtAY3l8VC8xql1TYFxG0bBOBIPpZB3PPmqDXA3oORajQBIqYAErIV2FZxk0x8Ml165IU3bDtjyTkDHDST2YpnMU8oN861rnzITOp3GoPawpCHUOZDve/iI28pv4orptXJAv1kNDVfYZrxo2m0/ufJjaxJnTpZOU1FOeaRsLWbjv1Fypnj61WcdmioQN+e3+E18TgXAkgwxosd8hlPCCrtHdKks1b/BXI8glebe1bpqJtDtKSvkNOtkbaNlY3P0DhRy2u1Z6TxjYJLR2aXge3N1k2wXL2Q2AaCB5ISDTYDW
  template:
    metadata:
      name: authelia-sessions-key
      namespace: authelia
    type: Opaque
