---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-oidc-hmac-secret
  namespace: authelia
spec:
  encryptedData:
    password: AgBjZL4Xy6dMGPf2Us7ue35BgIOJXb4GXU+8MbOieHnVxGGm/GfvAkcJZbbBMMZRzwYNLrvPCtwh2ivLtwZfZB60zUv7yVG02eVBwIsjwIPCgLh/xg16F3yUBjZbvdpWXF1AA439TOJg/bfavw0azB67xq+8XASNGHwE2WoaRtfTJreq66A8NQfFRbxYMbseKO6ENHrc3c3KIv4sowTMbfz4kVOzIx61mEe9/nNO3OGRsiBvIyo+wKOadfZAMSo4xb0Wn1qt8ZcAlXGyQpnyMjQmho2v6qF4unDeQzUNJ7KCbLBdTI0sWtxYxf13AFy5YWNx1K7E2EHeJ2ASgGB4y6lRwJdSAhW3NfSgJzocdwwk6VX/b+Tr/Vg8aBwkL8ogNHt91UsGphH2r5M/9ziBDIWtT9uRszOV/aZjuP0XZONUFkLDFTeCr4R3BM3p8I7sXyjyCfSJ2oZTcOzPHxdtil+Kg4fJH7dZgYuW6NC8Fy0gkAgW2/ur8KmB3jXNhDaYyLcZcpBemzy3ecW2wDqulJCvtahzW/m6rMlOuOgNmCmQwiu0LtPHXRd5mbIpMn+xWZrsCUr2N9LwV6LtaH+d9Bl5Xot6eR9/NyxDoGtdfOL6UwI+JFQeq7QbpYbEgWKSAX3EZn/kBRIFZ5dPIM61WeYu2vdK72fyAf40hVtXvNB8ylam42jHC01hBgJCn07awgJbUhD8zFwz9ZXk6C7IAs7jzi9SqfGY4vqGazBBal8oeVt6xgg5OpThdgjHUsq48JjEahjKqJRibUc61DvHwTH5YMhIYB6agrwMctrbdgWTv7eAzX1rxFQvL0r3Q7shR8g=
  template:
    metadata:
      name: authelia-oidc-hmac-secret
      namespace: authelia
    type: Opaque
