---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-sessions-password
  namespace: authelia
spec:
  encryptedData:
    password: AgA1CdzAid9lEa5nc7xo7avKmjGmiGYJTZN9FMhl6ovRHQYjIDdcutXx95douK1X6h5izIRHjOXv8GS94VydrYCK8ED5u7myDverXJXh5PC0QvDoojSD6Sy5wXPWDCc6VkTKi4YTqSTNN02bmzwzv+pbVHdnR6b9PScNn85OiWwlUfAE/GJ1oZ3LqmtiU9plwdJI5reE1q6VBaym6ajFncnonISEYSE0ibUylOTKl5oPlv1j6GZB0ByL4sUstJCL/FpF1YDMgD5ltJ5hoCpe+dcyy11yoyhAL4+g24vafy1IeB5CxrLmmjV3LCDOD+PYolHpk85prKNekWXy/prOLO/SWQxt6/JA0IBCUCZVhHKalGJnxfisdaW2BUtOtrDw2xbTxIYrcrmeZ0Xdy0r8xD4kjBCpIrkfvuvRgscxC0nAndJzRgFEo1fr8uyfwp+sfwenHUzdkzg9BrVrFfrSI4d+EX2wrWvPtlPhnTfVZLFT45MkDSIF76/zrSr6L4rOsBbutiBOl6GzCX3ZcU1A5tvVzy4lus+aJt+tukvG9mflsbiZB7xSeJ4kWtg/TQ7QlOqwiIaSnFWaAl+4Lg40o0x7QHLuWYiCtVEAeOOJkCop0IhYcKuHHegPT9cphh0HF+tFXAGaC9C06hhM3ejKW01l67PXXjAn4jvLdEMb/l9GlCfvMUxTkz+tJdpRlKpY0HD1GFrof2dRp0I9nQFISIZ65sHfz1SShMybfilMCkVJckNTrtNzpJVpw5FeJ/RgWnvycqlU0uW58OtCFnSdRyNL
  template:
    metadata:
      name: authelia-sessions-password
      namespace: authelia
    type: Opaque
