---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_OIDC_ID: AgCNldvHgc8dJZPJ0Sf3B9qlIQvRTdsziOpI+bdt/xQisPskVPShGdPQwSzpDbIWyF9ZKcywz93OVLtzStCdSFqBtvqAdbKKi1I7lVuHH2Fahts4ZJ8Y5nBF3sGkoWo9nNJDSQ3WTuQi3jAcvFjt94XZhy2CxdXYFlhaCN85J/CVAZXSH9YTxbFYzGx6mkjHbam+HtV9GXhtViYDqrmyzZewo87tPAC5zTyZ+VF+5xP26iJ5JqnZqTEkeVfKeAaAlZPzYxxsl9fgc6S9J8uClyaRW5yFwFgRLAC0brsnPGBzqJB/2VoE07tMa1BWdbO4ubD7IA5z+kPXLojcKxGA126RJI2exZ2HKlzII9RQJx8byf2qfMbWB3SI9xaQeJ8nn810SwJimx+v03Cf8nI/MDa1W97loYHU7h+hJYCe2qbwoMsxorWLWZE5x/qdcs8VIKNOG0m1BDCw08J9H69D4gy7OJHokM6KSYqFJso887hsGQWIKgySo4mXZep9X35uKMPk99ZYjyM9hHCYwEzZgWiRSwoS2nW9e00GjTDna0+bRXH2qpiwPijiKW9ezm4z/ju24RtQFjCOB88mTL1wEOo/mKQBI468dYjzkqIRP2AMNODtC1p81nkTrjssOfXWiR2Yo0zNudlIn6wF9FxMeYFRS85tWm2tiz3EwGW783DnNNfRkVSDD45vS1pNheu+lqUpgORJPuSeBH+toMvLgQze5LAqsif4YsTKJeRSHszoJQonfsSnOjf/5GBqaLnQcpftJazgKX+RRQkcUW/9ugFRu4jwwyVhKc8=
    GRAFANA_OIDC_KEY: AgAG0dhQ/2QURr/rSjdtGBemd1kVWbSXVuwuVZQ6GjEgKJuJjbAnMGR2TuJ88O1maNuxXBCTOWuKidXzOI75FUSnwdfc6dT/5PU5OVuhkJ2RO4+nY6kVX+cT2xehx/ZN0KPIhHtKef3r2brg+dbhBTp7E357HCu+JIBvBALffKb5IvVGTTHSrsdOnPEcNYJlsoKSZ6C5+bPIYpijKER4Nf0njVlzdIIbiJnPFly0waDYwtxt6fuiey3ogARUB+0/JYiezwODHjtMDKQI4xGwDZCRgPAW90eF8NukFLQdU1zzS4gKoKJW1JPE+JOIF/agdlXM4CqOdKxO73SLQ13jUHZ9B1vZxirJalngxcIoHPXGZDfaKxXq8/3XQGpBgHxbLnfwVUBrEhsaDRmvgVP0994badRmEP/ykq64o1SToP8mpRXwKZRC2lV60NsdOibyxA4Y0kJBhPE+zSksYydj2Lb3SFC1l/cBAUwBOdsAv+wEKWYxb5Tez4PyCCn2YoylmfLKhQN6/WUIRDQnpgWZtWvwKAbCpPS0fyM47PjUmRBbNPombTI0AYiDwCZbvBdha816yDhm7kBfZstc6V9Cx+eIxGhI2Nk30LFwqcW7N/tFJ0gDFDuqHsdgR/H0fuO/gCBOGpcR5iFbgYTfJ5snHZDrYEQxZv74es1QGFPI1vU1/QeodvhhZdie59PwNDr2FDcd3GBaNc9Vvtdj3UG+/LYzw2hVV50ITr4CD5omwwNAzgRp6/P3t5PIUat7Z8y+cnYA7t7/H9BSty211FvNM6VqsRprDNLZXfA=
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
    type: Opaque
