---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: inhibit-rules-config
  namespace: monitoring
spec:
  inhibitRules:
    - sourceMatch:
        - name: alertname
          value: NodeRAIDOperationInProgress
          matchType: '='
      targetMatch:
        - name: alertname
          value: NodeDiskIOSaturation
          matchType: '='
        - name: device
          value: 'sd.'
          matchType: '=~'
      equal:
        - instance
        - job
