---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: route-config
  namespace: monitoring
spec:
  route:
    groupBy: ['alertname', 'job']
    receiver: 'discord-info'
    routes:
      - receiver: 'null'
        matchers:
          - alertname =~ "Watchdog|InfoInhibitor"
      - receiver: 'discord-critical'
        matchers:
          - severity =~ "critical|page"
        groupBy: ['alertname', 'job']
      - receiver: 'discord-warning'
        matchers:
          - severity =~ "warning"
        groupBy: ['alertname', 'job']
