---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  encryptedData:
    password: AgAmJwFwCJVsiAXcz24PtIRVudN3/yIjBgfcIe8O9E97KG4Le06S9jJZIEd+veXRcoI83UEX3FS4U3qIDxRacHV2uh9/5jGT2n4KR1nKD5GxoX5BAm6UBYH7uPTR/YB5Km7CSAXAgNvHJSW6AbyD6jH+oonRsgfdDNbA+1WDSnO2E520TQ6OR00O/S7OqzY0fI7pbIxkYf0ZaX/RTNPwvtpLaIpUd84HXBZYlPziIq+FaidQrxLCFeVSM445/CANEVTNPq1Q8A3dZO6z5UZ3g5jmgPg0fi4iviqVnErE3Dg+wuhB7y75uU10Eui/nIi2Nx5woOhk3bXR75qJSdR3MXGLXGaH0C8//8wD4mvWQovwUHiC7wPs1kzc6B5HBzAjRxUj55344mFj2dJornfFkIK8uNaG/btSdY6tcIOHStjFwL2CpZ8R2t3hN2NUSjB3864+aoYF9JDvcw08DeSmoH1/rrdljTtx6HO5qXPTeZMYypcuzPRmGum603HaObjvl0lOgojGf1x567j7B/GhFlkealgB9MCcrTtVQPKrBjMdqq3KCBpQVWBPyF5CtrbMelY1tHkcPrFI0E9UMBWuUnIoWYRadWjMWRh6v5JIjblefqroRWvze5Dvw06dIgr8LTeV4jjFVIA5Dd/VfW5lAUiz1oIuQRGpc700hzoiKnvCEhn1tZ4xX4eCoBm6RK4ObFo=
  template:
    metadata:
      name: pihole-admin
      namespace: pihole
    type: Opaque
