---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  encryptedData:
    password: AgCT3EnrCY0AVP203xLU5I7gwol4dxYcMNPjUH4eggsD7i/VXHJh2CDBnGncBIieBHwyo2bgdS75D22jzO9KUAranwjSLGk+O/ssL6Pz2slPXz590sXiBcmePPS61EmX/92X8HjtTribR7WTlRGzgj6yoiP21knKGXA3pe5v+JzuSmZCgEJL9fl3qfqNSuwzWnhF2hMPxlmyURMzEPMo5bDWjsUrPtF0WEUud/H4svCoNUmgvSBWmip6DrzyR+pDD2rOCNdsWTGlE2qKtF1MMfuksv1BlbVgMl14smr/AXyQhgP6dWUculZ0zN2eCMF+CcqYLbm62s9H2ARE71tQ0Z72s8Cz5Pd379tr8tlkzibqODPteLhxIWnAKex3l30y7OFhtW15qkzseABPsWj5hiF65q+IbvxkS1s32JttmnRNPp0F0bx3BU0pALsWjVq3mdGSOycupG+FnWYQ7X4u8zVokY/lckKrKnhcFEdq1Foe56MqY8I3WtOJWPizjh5qxNShqIEklLLbu98Llq2sV5mZtYbmQVhjhBUBj76t+9+VEG2OKCuj85RgSq/8DZY1BBcv8Sgcg4W/2uWNSfzjCHNqEKd9/jvjmfrHkD1u5mXq191maKAmz6LzdYP2fUcHnKEfVMm5+HjrtLvcfjADKHWXqshMGehMsro68hwuj3m0oh5Cgr5hhHIzlwXzglTrCurDUGgSkv8GlQIaRlS1
  template:
    metadata:
      name: pihole-admin
      namespace: pihole
    type: Opaque
