---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-disk-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: narwhal.raft.lutris.house
  share: /srv/nfs/kubernetes
volumeBindingMode: Immediate
allowVolumeExpansion: true
