---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forgejo-certificate
  namespace: forgejo
spec:
  dnsNames:
    - git.raft.lutris.house
  secretName: forgejo-certificate
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
