---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-monitor-forgejo
  namespace: forgejo
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: forgejodb
  podMetricsEndpoints:
    - port: metrics
