---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-pg-user
  namespace: forgejo
spec:
  encryptedData:
    password: AgAl5Nh69J2EQ3D3jyWbaQNl1f7Q8v877DdQpBmy1Qw6OBuiI28ww7Pl5L8gIRpllMIXma2Z6fjC4PZqTUP8dt598tcUMbBz8CziI0jt5F1IsfEI9hx3zGRkvs7CUIrgtFIHpUidyzVaefwxcpqrsq2Y7zGKlBSSM6/1vYLv1Yg9mSKWS5BDgb+9VA8kee4xbT/Me5QpVXkU/NXV09jxw3Y8hhZUDXuucx28gVXu8jaA6R8mDcxl48NzhI0xdoimdi9Q77RjDUV3i9CPeH4ZGZdfLxGPk2Twdw/vXlKqeCy+Fts98+tLW9wR/3WL9R9YtYVyYP3FU2ZO14rLnSXiW95vrtKTw6CQ47UY9bLKN+IsT5ayv6S8uBAYwQjbieQ5tbmUvLyHEoRW/3eE4nyM0tWP4oO+KChcyH/r+FvDPP9ctBIugDsxjV8gXEkNp6iC+NMcpy9HECXNp7xh7ay9JwGNjVPJ9w2EOHKoBJ0ymvlZ1Zbc6puFC2D3hq184N2bJg/xd/sx+FncjppoYa8bVxLnxnPtsNLgIRvWRZSqI/gWxksPbAoYEs1xGDhRCLiPfdubCqB+i3lOBwubA94CVHBLW25qo69VVrd8b5qC+SDtVkKfJ6saYsRt8X78yHlHc/s5KJjlTrXgkkoJpe8WyLsBzhsnpiMssa+R06cRIG98MEiRd7FXtQrw5Di6czcw6qdutHkCKCpDz0Oh1tKGGZ7oNdOnO+7OAqg4pnebZtHGug==
    username: AgBSfNjdnkVBSuwfxCZuzs7cMfDY3QtDNr3VOCmE93PeqqrSarokAxI0VUZf3q0s+pIVCA0Zbe8SC6dVekVFkhdRf8bvGiqgxqn3G5GnFKiF0zvcIvadoTlmVS2iqBquwZeBht6wf6Bywpj1QVVkhIuQtr7xnOwqYcAhf+uW3zfQzTDMkuJSlLbrx5nufIZlpn9nSZmQRbxdG0qq/B8h1p6dzJvZ0xZiStSZU70ZKblzrSe8q53zuklrGDeVfbI4oFVPwBzcUN9E3ociX4FGVdeq97KGl6QhH0YoIrNUtOg+GdI7NO7HMj69iVHkXGl6z19ZxSS1daU8YnJrjT8NScfiE7xu42YNbalNbGB4jFcai2/ZkdXxKCWzI/NCXO7mGP5yB42zF1X0QHtxBZpuyCd20lSmWRY3nusJ1kmOSmV6470/gRXg/0rL2x6XtyH05tLmbZ55TK3ErEj7DullP7qllhtxyZXxCjDUq1eh39yCxFW9YzmUEt78q1LIuWV0PWsOYUH9mv34VyQ2lQlxXsupcsgjK7Iq0vuk3avFYFi6c9WviKEi+DB5YIZsJJfF5hOs22e6ku3xG2ee78/qIwg1TiACvWIsSFDqSjd0KY9bE51Ew2g+MZyifvoAHvHEQuHYCRV6nurY8nsyYAW9yC4suzf4OzcjeidftR0B8x0MIev614nupcmrGp7YoaQz34+gmugAjXFq
  template:
    metadata:
      name: forgejo-pg-user
      namespace: forgejo
    type: kubernetes.io/basic-auth
