---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: forgejo-ssh-route
  namespace: forgejo
spec:
  parentRefs:
    - name: forgejo-gateway
      sectionName: ssh
      group: gateway.networking.k8s.io
      kind: Gateway
  rules:
    - backendRefs:
        - name: forgejo-ssh
          port: 22
          group: ""
          kind: Service
          weight: 1
