---
replica:
  enabled: true
  replicas: 2
  persistence:
    size: 5Gi
    storageClass: longhorn
clusterDomain: polycule.raft.lutris.house
auth:
  enabled: true
  usersExistingSecret: authelia-sessions-password
  aclUsers:
    default:
      permissions: '~* &* +@all'
      passwordKey: password

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
