---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-romm-certificate
  namespace: romm
spec:
  dnsNames:
    - romm.lutris.house
  secretName: ext-romm-certificate
  issuerRef:
    name: cloudflare-le-dns01-issuer
    kind: ClusterIssuer
