---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: romm-http-route
  namespace: romm
spec:
  parentRefs:
    - name: romm-gateway
      sectionName: http
  hostnames:
    - romm.raft.lutris.house
  rules:
    - backendRefs:
        - name: romm-www
          port: 8080
