---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-data-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-disk-csi
  resources:
    requests:
      storage: 20Ti
