---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: romm-db-secret
  namespace: romm
spec:
  encryptedData:
    password: AgAIjwwahWLfzuIiIQuq9elsR5lp3K08ezdCawj3znOmoMH9si5PMajPAAFTuiGnWsH41SzFGLHtOW2UBLiNd1dFWWbqXq8FKfo/tKBvgZqHF+9y5A8ShpgPiKWcWPbVTtO8FJeBRnlBSw1I495l5prSGhm4mkfPMxWcLPoVmlatGoE3zWB9KmwRjNyZ+etnBvdsMGZtjs/lhAQC6CWqu0zIe6ZIeMoQMCGsSK9QQtVxGgBRxyIamk6WfW5RqzboNeP655ldo0dyXnQC0rkZNI0OcvIGjN1UlJPPXwrc/n34chPsy3sf1X2pKZ4padP4kulEpCTSAeVdHefMA8Ggx/KZEmHQfGCtdVIHJINJpjDBDQyt+Yebt3BjvgfSHldrEapqzhlP4wqP4zczhqGH8fCXY/8QXXi2i2X286OGyCq6P+2iFkAZXRsQWWlUB/eL/4nHe2HzTXoDvfJhwh5Fq/byzXuQJkr6Pn4gmu4IwnOF32cmCE37wmAS8ylca3muVC2lEjIv0zC5wDy64O58R5Mr53M8Yjr5w5LNdG3pld2Ss9VaBKJ5ZYpAf3SotFT+h1wcX4mxSuqMR6bvRQ5qPZ1N8KLJRGtIqCIO9h5lMLCMWUl62t4ScPXhFspVHQarmyjbSObCo1BWxFuZB/QRVCWlbzD6XOzwENjzrln85y+89UmIEuT3O7GMBMXTwCmVWKI2ioIeFJnrWU/n5nqzcOWJz2AgFmr1kUo=
    username: AgAlRzuL2DcE+hjkwvTuBroB+52ojlGKJQo/2grGV2n6Fc3IaMLeD+YM5xf4Tq8mK8GnZJAptVUWWx5Dd5xWq4Mh4NkebWEbyyjVPpr8ODt0noO8s3rOGCh847yxObn2MppVfqZDAYpHYyEV7QqUyPTD2atGnnvU2ICab4ZPPYzsbmoH6urzhSDLJ2SbS+cuKCGwaYbnyfuZnTBrcz6MxGH4dwpeGXfMea+7U/OQIyslfpnM3HXeZBGaWoGqQtPGd1XkUOlOF0flFfeceNhiALq228kwMb6y5tOhptT3IPa6AX/YsfYxBA2rDkaNBTXMQztWpje66pbTjgC5yC95KnXQjzKBde4qJoU70cd/XU8J5pjEDxBQGfe9xOkqI+NWAJ8KsyEMYKRo08Rfj7RqmuOf8cuX9C8WcfKz8QrggVbOmTHGvPMb1IpgF3uFB+ibg8q+g5lViKgi2NKb3QGLom/6Ux9Wr/Xq1Dtn1Z1ZvpuMW2ZVMPWow17MX9WNYeYVXPucXJ+eUv7Tc7WQJyPVyGQZCuFPD9edxjxxzcqRn8nVTu1v2MBGkaWwk2n1UF4uhiKMNwfEjF0dasK45PtJUStxUNl7oXvJ04XC/gxNr42hcUgGqsRrXE4o5246Zhyfk0x+Hz78dOk98stWBCp1/ugdVblITcXfSpRi85Ch/PlDs5KgJ/hFmp0Hmp/+zX8gGd59Ouj0
  template:
    metadata:
      name: romm-db-secret
      namespace: romm
    type: kubernetes.io/basic-auth
