---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: romm-valkey
  namespace: romm
  labels:
    app: romm-valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: romm-valkey
  template:
    metadata:
      labels:
        app: romm-valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:9-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: valkey-data
      volumes:
        - name: valkey-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: romm-valkey
  namespace: romm
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    name: romm-valkey
