---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immichdb
  namespace: immich
spec:
  instances: 3
  storage:
    size: 8Gi
    storageClass: longhorn
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-pg-user
      postInitApplicationSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
