---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich-http-route
  namespace: immich
spec:
  parentRefs:
    - name: immich-gateway
      sectionName: http
  hostnames:
    - immich.raft.lutris.house
  rules:
    - backendRefs:
        - name: immich-server
          port: 2283
