---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-pg-user
  namespace: immich
spec:
  encryptedData:
    password: AgBAzHPE3oCzhRYjawWjtCdvawIxw1RZTcizzvHzzqLdP4CVyyhLrO0szTo8QZ6wNiPimSfoQQoPip6DDxjnWBjfutxacrn2B239njESvVIGPZNeIZkdQcDOeTnUQOLvXBMNOjx5VBSXuUvxFf3EfvQlfH3ytyDhNe93oPjLOPQmVJwXMER7EfYEELWXKh/2wrwq1uxam7t+x1HxgGL56pPmV3pKkVGFU2KkqqZPseJa6ZI+HswfY0GI9VC2onwC65O2omCGexgeF2BHxY72V3UhzYMkYse7p3uVlkYLzAeTLWPJmTjpkmE8/OMCh3uz2eMkRUrWmWSbqjfZ2M5gSx19Kveu2HQkql1LhX3ChntdIdZua0OSrtndQUXj+IpxKA3iS3MTwdApfG9v14DwP5HwgkA46sDaWTXQcg6QW2xuOM55Q9f9DRx52p79KGZ2cJIGU3NCL0M8cOUqRXUpQRA0zlCvwHGhaQ9/U9EYAaJzSbzXlJJHKpfu36pEp8GD966K4Va7F53aBxRlg6uh2O08/9U6hvUhHO3f4uJAfdLxbDA2Q6Bdrvy15yHi0Vg/X/9XoHeNMY7X8rJTGd8rSKBL+1uMZwf1ETOc2AA9xzlN7hzcw20wuqXpuwmLBlvereX17dVv6p1XRuqNvvY+mu9aQPdwf+wY4V/uyzyhozq3LQXAV/MQcIubk1OT4Hyp/zFQhgSR5maaztm0q7zqxTYmOGpKSsJKjsU=
    username: AgCH4ziasgyobR70h4z3QY0YyAc4hcvUnS4NbUPmmy3zt7O+kGfS7xx9ovUc61fzjG+ausjVct0VK2Cr+QPeo8eJiBL6Yc8ApB9Zizp4/l8GGBRjwjqTDC5FvX7tdPWpin17Y+114IJzXsdoaHiIsOZtADSL/0EZ14OwNTvnkfVhTO3AAu/20a7kDQ7WNsNnwd5/TP0NipuRqrVbooyMMyzcHvXeWfXC2YcrchgueWeUWGpfWYf0DgKdkbA9fmPyUvyCeKvb8295as+/G7/bdkB1i4e2bhXqp93ifaaV9dGkiA4FZbUxhyVMM8Vj2VwS9C/aAdheQbUV0Jv13t8ORR+8wUgTEz1GU9d+Wj0bbFjW+JLxkgDEBjHTvlAEb0UtQ+iLaf8Kd5EYync2yQp9MPSWf6a3zvb675fEFIv1h0wv1Z4cAxJmckAJO+UCHChwHafj1ICL8UhSqBjfferXlehSuf4qrlPamvZPIpYyMWbIbIxtt0HlzVUw+6o2ygiojwkJ2p7vR+8z+ayEIRPzxZqQ72dBlu3yUmJ0DMcvCw2Ork0B0bORn+qGHoDWS/j9in8H1ge/ADPvryWm65IyXSToKHPgr4K5UvEYS1Uvphg6SMkw4GOSPsG9pV7aEXnv+GpuGEw+egt3wYi0tl3WFnXI2ZvKC4So1cRdgTJM1zz9Bh8sRd/wQPT1Z7tZH5MbfQtNLYpdT4c=
  template:
    metadata:
      name: immich-pg-user
      namespace: immich
    type: kubernetes.io/basic-auth
