---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs-library-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-disk-csi
  resources:
    requests:
      storage: 2Ti
