---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-monitor-immich
  namespace: immich
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: immichdb
  podMetricsEndpoints:
    - port: metrics
