---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cryptpad-sso
  namespace: cryptpad
spec:
  encryptedData:
    sso.js: AgBry9WFgafPQ7Ov9WnZnM0TzZ9J/lK3eFtbqp0m1sWyeKaxtu324ioPcehMWr6pBTYn3yfjSD2wd6zU4rXHekn/ddWJzx7oL2UOiFbawXOT3Xh5HALEv8qERcgOYip7HYrZe7slKjQMwFQSaebx4l588u69K5LeWauQn9J8y4lQE0dwFkll+TeEAmVurNz3NKf8w4AMmL+rqvg0mw9qmIjafHoHtS33tbGf+tfyNUqdgZ6fOTscnventw/Qtv8hDA8lqXTOASNKrNsnDpuQ84H/e6MWo64kVFyTTnLgb26wY9Kc9LZKYmIJB0SJyttOjEAELc1HcFlf0UUSqX3BtFrFAwfgMFk4AfABL1j9u4dWGR/NYS7OZtb5DKPKJfIo0RvyOYLLLqio4ZGVsiz5ZTwpAuzTm/EskFAn+zo1mtnrjneKGPLSsSkqO75OxGxtlSttYfG6As3svYHtF6thyzeNFN9PgG3VaGsaCYn9/lzgk/z/DhIxIEeoZeOis4OKkKFJwW9NRCRE1uh1No7DS6F3aeqMpmrYBlavJ/5vdharLuK2EzCMj1kNrajVG8XPjgUs8MGABB9Bki/Gf5Lm5mp/yiab9GDlvKG+uwwxwNQDffv+OUIi6/k0C+RkAHa0YsrEbWyhX2UyUj+HDiOi7nWf8MR4UimvQIA7cBY2I5q7xos5yHu5Yf6x6Zeof6/UdFfYW4jbQrjRuTChvEfx6UZ69DhhwA253EsKm8nUXh95lrCJUYcZRaXq/fDPaRPasaLLYkC3DqJfVJsLrggop0pICuaiUY8pmao/PO9mIjp8Q+g7MuvqqhvOXY/n81jkMKqu8nA2T/qjmFyrkIczNxVrCxIvqE5yI1BCmz74120HN0PVbUbUc2TSbOJPZGeHC1gdWJyOraCQuEUx6XtZ4GY6BabEqrHOOoHR88hy5pDKyUj4R110eXfPSb0NlhOSn6sLJylUBIwfORIMfBwhH42tDBFohGvDmsilIajt3pM2G84E6ShJkykSXz6C5Os5KXTA6fXl72VZ6Oz1VC5CU6ztHLS9dXcWTM1Wjah64KVWu0kVz0ny6gG1D94VKOPwqIiwUL9nl5HMAXQxSj5+UdEBmtSFE4r+6VdPwCNzE/loj5f9I7wDsiGRTO7gjwn0c4QdO/AGIh2WdTDqAfhXT2ypgU6mM6F2BHzmv2nt/ESMKecUcyqVizwxdjfS7Tb3E8h2q2XV4a/5aYxchQkIuXc0EMa9PvG7sJ2ciJisqZsSbc/bXRbiDtIU4Q1N0d/P8iy5J1stQkyqefZVkxbz+kwb+Gd0W6jSVHqA567UqXEN7fEcMoaE+KSrY/s1U7haqxXdBdYEecCMNe0TJYjwtQ==
  template:
    metadata:
      name: cryptpad-sso
      namespace: cryptpad
    type: Opaque
