---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptpad-plugins
  namespace: cryptpad
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: longhorn
  resources:
    requests:
      storage: "1Gi"
