gateways:
  - name: dashy
    hostnames:
      - dashy.raft.lutris.house
    listeners:
      - name: https
        port: 443
        protocol: HTTPS
        routes:
          - name: dashy
            service: dashy
            port: 8080
            hostnames: []
