---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejoexpdb
  namespace: forgejoexp
spec:
  instances: 3
  storage:
    size: 8Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: forgejoexp
      owner: forgejo
      secret:
        name: forgejoexp-pg-user
