---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: external-nut-exporter
  namespace: monitoring
spec:
  jobName: nut-exporter
  targetEndpoints:
    - targets:
        - narwhal.raft.lutris.house:9199
      scheme: http
      labels:
        ups: eaton1500
      params:
        ups:
          - eaton1500
