apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: rule-node-rules
  namespace: monitoring
spec:
  groups:
  - name: node.rules
    rules:
    - alert: ''
      expr: topk(1, max(label_replace(kube_pod_info{job="kube-state-metrics",node!=""},
        "pod", "$1", "pod", "(.*)")) by(polycule,node,namespace,pod)) by(polycule,namespace,pod)
      record: 'node_namespace_pod:kube_pod_info:'
    - alert: ''
      expr: count(node_cpu_seconds_total{mode="idle",job="node-exporter"} * on(polycule,namespace,pod)
        group_left(node) topk(1, node_namespace_pod:kube_pod_info:) by(polycule,namespace,pod))
        by(polycule,node)
      record: node:node_num_cpu:sum
    - alert: ''
      expr: sum(node_memory_MemAvailable_bytes{job="node-exporter"} or (((node_memory_Buffers_bytes{job="node-exporter"}
        + node_memory_Cached_bytes{job="node-exporter"}) + node_memory_MemFree_bytes{job="node-exporter"})
        + node_memory_Slab_bytes{job="node-exporter"})) by(polycule)
      record: :node_memory_MemAvailable_bytes:sum
    - alert: ''
      expr: avg(sum(rate(node_cpu_seconds_total{mode!="idle",mode!="iowait",mode!="steal",job="node-exporter"}[5m]))
        without(mode)) by(polycule,node)
      record: node:node_cpu_utilization:ratio_rate5m
    - alert: ''
      expr: avg(node:node_cpu_utilization:ratio_rate5m) by(polycule)
      record: cluster:node_cpu:ratio_rate5m
