apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: rule-kube-prometheus-general-rules
  namespace: monitoring
spec:
  groups:
    - name: kube-prometheus-general.rules
      rules:
        - alert: ''
          expr: count(up == 1) without(instance,pod,node)
          record: count:up1
        - alert: ''
          expr: count(up == 0) without(instance,pod,node)
          record: count:up0
