---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-authelia
  namespace: argocd
spec:
  encryptedData:
    oidc.clientSecret: AgBbHi/BDKZJWmbqvpS52Slfr4VQweDfQUr1tmWeHre1XOp0kJkPzLSuvs9lCbghQwl4a9yd4HqiB76hxn91RUmvOKSC842SSkrd9rRHjAVmxvtkkGkSDu+7dyXY+K13LRy2igdL2eSzs2YTYEyqszmxf+tXpl1OL8LtACrYy5ysbfNCrSAPkIRegrOwU+KNJLkuHubUImwUex6ruYczoQfUR3BIiYC1YNFgHg4aIfARrbp8KxMTNOWdgB7BNnR2fWu/ZuEBKnWiYHLonI7rwH/vMgB4kyfPt1h0dc38pE2Q1TGmbszHvX09GzQhYQSsMM5XZgP8YMzWrLZD9UIIacPWQyOGMGlWLTjWulA+RW10qyupXEtYNWtLpoTktxAU+6dGeCSCDDJEvogloH40tcXUOHzATqYh3NYapTkJQhCfEjnp8cijWBAF2GJvhDPDRwiHCHIA5tL/DonPtzpXMZGe2ptdiD76Fxk0pCuJqvmLdDMufODztadx/Jyg+PLvlIvPlaJSXVPqZ26pxbdavf6UOvQK6ZtFLmO08jhL5YytAE0EjRqM+3k79pUXApZTW7fHUdh19DnuJppl7VLgvxMsoQoE/YFeDlfLGWwVayTlNJJUG+mCMQvDja1dsWPFdlmVoD7ckZyUwA9xpkRf2Uirpq4MSwg7kuSCUbdfrHYRlqbvBjFcis+fWhTc8srKswCkIQGjuB2o2snRlJ5CMeRWL5BSX3S6KeqvT0cgMZpYld2tCO/twFz0mJZGIHkwXgBuiGTag7eFoWokX2jX1lv/ReKmbVMj8rM=
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-authelia
      namespace: argocd
    type: Opaque
