---
instances:
  - name: "gwams"
    repo: https://git.raft.lutris.house/soupmix/gwams.git
  - name: "gwids"
    repo: https://git.raft.lutris.house/soupmix/gwids.git

certificate:
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
