---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: ztunnel
  namespace: istio-system
  labels:
    app.kubernetes.io/name: ztunnel
    app.kubernetes.io/instance: istio
    app.kubernetes.io/part-of: istio
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ztunnel
      app.kubernetes.io/instance: istio
  podMetricsEndpoints:
    - port: ztunnel-stats
      path: /metrics
