---
apiVersion: v1
stringData:
  alertmanager.yaml: |-
    receivers:
      - name: 'null'
      - name: 'discord-info'
        discord_configs:
          - webhook_url: {{ discord-info-url }}
            send_resolved: true
      - name: 'discord-warning'
        discord_configs:
          - webhook_url: {{ discord-warning-url }}
            send_resolved: true
      - name: 'discord-critical'
        discord_configs:
          - webhook_url: {{ discord-critical-url }}
            send_resolved: true
      routes:
        - receiver: 'null'
          matchers:
            - alertname =~ "Watchdog|InfoInhibitor"
        - receiver: 'discord-critical'
          matchers:
            - severity =~ "critical|page"
          group_by: ['alertname', 'job']
        - receiver: 'discord-warning'
          matchers:
            - severity =~ "warning"
          group_by: ['alertname', 'job']
kind: Secret
metadata:
  name: alertmanager-config-secret
  namespace: monitoring
type: Opaque
