---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.16.60.1-172.16.60.200
    - 2001:5a8:4bd5:ef00::f00d:cbe:0/112
