apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/component: speaker
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/name: metallb
  name: metallb-speaker-monitor
  namespace: metallb-system
spec:
  attach_metadata: {}
  endpoints:
    - attach_metadata: {}
      honorLabels: true
      port: metricshttps
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - metallb-system
  selector:
    matchLabels:
      name: metallb-speaker-monitor-service
