---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  project: system
  destination:
    server: https://kubernetes.default.svc
    namespace: authelia
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data/identity_validation.reset_password.jwt.hmac.key
    - kind: Deployment
      group: apps
      jsonPointers:
        - /spec/template/metadata/annotations/authelia.com~1checksum-secret
    - kind: StatefulSet
      group: apps
      jqPathExpressions:
        - .spec.volumeClaimTemplates[].apiVersion
        - .spec.volumeClaimTemplates[].kind
  sources:
    - repoURL: https://djjudas21.github.io/charts/
      targetRevision: 0.6.3
      chart: lldap
      helm:
        valueFiles:
          - $values/authelia/values/values-lldap.yaml
    - repoURL: https://valkey.io/valkey-helm/
      targetRevision: 0.9.4
      chart: valkey
      helm:
        valueFiles:
          - $values/authelia/values/values-valkey.yaml
    - repoURL: https://charts.authelia.com
      targetRevision: 0.10.57
      chart: authelia
      helm:
        valueFiles:
          - $values/authelia/values/values-authelia.yaml
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: authelia
      targetRevision: HEAD
      ref: values
