---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  project: system
  destination:
    server: https://kubernetes.default.svc
    namespace: authelia
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://djjudas21.github.io/charts/
      targetRevision: 0.6.3
      chart: lldap
      helm:
        valuesObject:
          replicaCount: 2
          deploymentAnnotations:
            argocd.argoproj.io/sync-wave: '1'
          externalPostgresql:
            enabled: true
            fromSecret: lldap-storage-app
            uriKey: uri

          lldap:
            baseDN: &base_dn dc=raft,dc=lutris,dc=house
            secretName: lldap-credentials
            jwtSecretKey: jwt-secret
            keySeedKey: key-seed
            ldapUserPassKey: admin-password

            forceLDAPUserPassReset: true

            httpHost: "::"
            ldapHost: "::"

          bootstrap:
            enabled: true

            groups:
              - cluster_admin
              - monitoring
              - media
              - cloud
              - development

            users:
              - id: authelia
                email: alicelutris+authelia@gmail.com
                passwordSecret:
                  name: lldap-credentials
                  key: authelia-password
                groups:
                  - lldap_password_manager

    - repoURL: https://valkey.io/valkey-helm/
      targetRevision: 0.9.3
      chart: valkey
      helm:
        valuesObject:
          auth:
            enabled: true
            usersExistingSecret: authelia-sessions-password
            aclUsers:
              default:
                permissions: '~* &* +@all'
                passwordKey: password

          metrics:
            enabled: true
            serviceMonitor:
              enabled: true

    - repoURL: https://charts.authelia.com
      targetRevision: 0.10.50
      chart: authelia
      helm:
        valuesObject:
          pod:
            replicas: 2
            annotations:
              argocd.argoproj.io/sync-wave: '2'
            kind: Deployment

          secret:
            additionalSecrets:
              lldap-credentials:
                items:
                  - key: authelia-password
              authelia-config:
                items:
                  - key: smtp-password
                  - key: storage-key
                  - key: oidc-jwks-key
              authelia-sessions-key:
                items:
                  - key: password
              authelia-sessions-password:
                items:
                  - key: password
              authelia-storage-app:
                items:
                  - key: password
              authelia-oidc-hmac-secret:
                items:
                  - key: password
              authelia-oidc:
                items:
                  - key: argocd-id
                  - key: argocd-digest

          configMap:
            theme: auto

            telemetry:
              metrics:
                enabled: true
                serviceMonitor:
                  enabled: true

            default_2fa_method: totp

            identity_providers:
              oidc:
                enabled: true
                hmac_secret:
                  secret_name: authelia-oidc-hmac-secret
                  path: password
                jwks:
                  - key:
                      path: /secrets/authelia-config/oidc-jwks-key

                authorization_policies:
                  monitoring:
                    rules:
                      - poilcy: one_factor
                        subject:
                          - group:monitoring

                  development:
                    rules:
                      - policy: one_factor
                        subject:
                          - group:development

                  media:
                    rules:
                      - policy: one_factor
                        subject:
                          - group:media

                  cloud:
                    rules:
                      - policy: one_factor
                        subject:
                          - group:cloud

                  cluster_admin:
                    rules:
                      - policy: two_factor
                        subject:
                          - group:cluster_admin

                clients:
                  - client_name: ArgoCD
                    client_id: '{{ secret "/secrets/authelia-oidc/argocd-id" }}'
                    client_secret:
                      path: /secrets/authelia-oidc/argocd-digest
                    redirect_uris:
                      - https://argocd.raft.lutris.house/auth/callback
                    scopes:
                      - openid
                      - groups
                      - email
                    authorization_policy: cluster_admin

            identity_validation:
              elevated_session:
                require_second_factor: true

            authentication_backend:
              ldap:
                enabled: true
                implementation: lldap
                address: ldap://authelia-lldap-ldap:3890
                base_dn: *base_dn
                user: uid=authelia,ou=people,dc=raft,dc=lutris,dc=house
                password:
                  secret_name: lldap-credentials
                  path: authelia-password

            access_control:
              rules:
                - domain: '*.raft.lutris.house'
                  policy: two_factor
                  subject:
                    - group:cluster_admin

            notifier:
              smtp:
                enabled: true
                address: submissions://smtp.gmail.com
                sender: 'Lutris.house Authentication <noreply@lutris.house>'
                identifier: gmail.com
                username: alicelutris@gmail.com
                password:
                  secret_name: authelia-config
                  path: smtp-password

            session:
              remember_me: 3 months
              cookies:
                - domain: raft.lutris.house
                  authelia_url: https://authelia.raft.lutris.house/

              encryption_key:
                secret_name: authelia-sessions-key
                path: password

              redis:
                enabled: true
                host: authelia-valkey
                username: default
                password:
                  secret_name: authelia-sessions-password
                  path: password

            storage:
              encryption_key:
                secret_name: authelia-config
                path: storage-key

              postgres:
                enabled: true
                address: tcp://authelia-storage-rw:5432
                database: app
                username: app
                password:
                  secret_name: authelia-storage-app
                  path: password

    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: authelia
      targetRevision: HEAD
