---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cat-stuff
  namespace: argocd
spec:
  destination:
    namespace: cat-stuff
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  source:
    repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
    path: cat-stuff
    targetRevision: HEAD
    ref: values
