---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cat-stuff
spec:
  destination:
    namespace: cat-stuff
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - kind: StatefulSet
      group: apps
      jqPathExpressions:
        - .spec.volumeClaimTemplates[].apiVersion
        - .spec.volumeClaimTemplates[].kind
    - kind: Secret
      jsonPointers:
        - /data/adminPassword
        - /data/cookieAuthSecret
        - /data/erlangCookie
    - kind: StatefulSet
      group: apps
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  sources:
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: cat-stuff
      targetRevision: HEAD
      ref: values
    - repoURL: https://apache.github.io/couchdb-helm
      targetRevision: 4.6.3
      chart: couchdb
      helm:
        valueFiles:
          - $values/values/values-couchdb.yaml
