---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cat-stuff
spec:
  destination:
    namespace: cat-stuff
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - kind: StatefulSet
      group: apps
      jqPathExpressions:
        - .spec.volumeClaimTemplates[].apiVersion
        - .spec.volumeClaimTemplates[].kind
    - kind: Secret
      jsonPointers:
        - /data/adminPassword
        - /data/cookieAuthSecret
        - /data/erlangCookie
    - kind: StatefulSet
      group: apps
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  sources:
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: cat-stuff
      targetRevision: HEAD
    - repoURL: https://apache.github.io/couchdb-helm
      targetRevision: 4.6.3
      chart: couchdb
      helm:
        valuesObject:
          clusterSize: 1
          persistentVolume:
            enabled: true
            storageClass: longhorn
            size: 2Gi
          dns:
            clusterDomainSuffix: polycule.raft.lutris.house
          couchdbConfig:
            couchdb:
              single_node: true
              uuid: 5033d0c4-6da6-4135-902e-e58a5edda3ef
