---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: oci://quay.io/jetstack/charts/cert-manager
      path: .
      targetRevision: 1.20.2
      helm:
        valueFiles:
          - $values/cert-manager/values/values-cert-manager.yaml
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: cert-manager
      targetRevision: HEAD
      ref: values
