---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - path: cnpg
      repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      targetRevision: HEAD
      ref: values
    - repoURL: https://cloudnative-pg.github.io/chart
      chart: cloudnative-pg
      targetRevision: 0.27.0
      helm:
        valuesObject: {}
