---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: code-server
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://github.com/coder/code-server.git
      path: ci/helm-chart
      targetRevision: v4.114.1
      helm:
        valuesObject:
          image:
            tag: 4.114.1
          persistence:
            storageClass: nfs-ssd-csi
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: code-server
      targetRevision: HEAD
