---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashy
spec:
  destination:
    namespace: dashy
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - path: dashy
      repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      targetRevision: HEAD
      ref: values
    - repoURL: https://git.raft.lutris.house/api/packages/the_raft/helm/
      chart: gw-helper
      targetRevision: 0.1.4
      helm:
        valueFiles:
          - $values/dashy/values/values-gateway.yaml
