---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - path: external-dns
      repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      targetRevision: HEAD
      ref: values
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      targetRevision: 1.21.1
      chart: external-dns
      helm:
        valueFiles:
          - $values/external-dns/values/values-external-dns.yaml
