---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejoexp
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejoexp
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: oci://code.forgejo.org/forgejo-helm/forgejo
      targetRevision: 16.2.1
      path: .
      helm:
        valuesObject:
          replicaCount: 0
          global:
            storageClass: nfs-ssd-csi
          clusterDomain: polycule.raft.lutris.house
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
          gitea:
            metrics:
              enabled: true
            config:
              server:
                ROOT_URL: https://gitexp.raft.lutris.house/
                DOMAIN: gitexp.raft.lutris.house
                SSH_DOMAIN: gitexp.raft.lutris.house
                ENABLE_PPROF: true
              database:
                DB_TYPE: postgres
                HOST: "forgejoexpdb-rw:5432"
                USER: forgejo
                NAME: forgejo
            additionalConfigFromEnvs:
              - name: FORGEJO__DATABASE__PASSWD
                valueFrom:
                  secretKeyRef:
                    name: forgejoexp-pg-user
                    key: password
          persistence:
            size: 4Gi
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: forgejoexp
      targetRevision: HEAD
      ref: values
