---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data
  sources:
    - repoURL: oci://code.forgejo.org/forgejo-helm/forgejo
      targetRevision: 17.1.0
      path: .
      helm:
        valueFiles:
          - $values/forgejo/values/values-forgejo.yaml
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: forgejo
      targetRevision: HEAD
      ref: values
    - repoURL: https://git.raft.lutris.house/api/packages/the_raft/helm/
      chart: gw-helper
      targetRevision: 0.1.4
      helm:
        valueFiles:
          - $values/forgejo/values/values-gateway.yaml
