---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gwams
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: gwams
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: gwams
      targetRevision: HEAD
      ref: values
    - repoURL: https://git.raft.lutris.house/api/packages/the_raft/helm/
      chart: cat-web
      targetRevision: 0.1.1
      helm:
        valueFiles:
          - $values/gwams/values/values-gwams.yaml
