---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: system
  ignoreDifferences:
    - kind: ValidatingWebhookConfiguration
      group: '*'
      jsonPointers:
        - /webhooks
    - kind: DaemonSet
      group: '*'
      jqPathExpressions:
        - .spec.template.spec.containers[].env[].valueFrom.resourceFieldRef.divisor
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.29.2
      helm:
        valueFiles:
          - $values/istio/values/values-istio-base.yaml
      chart: base
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.29.2
      helm:
        valueFiles:
          - $values/istio/values/values-istio-istiod.yaml
      chart: istiod
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.29.2
      helm:
        valueFiles:
          - $values/istio/values/values-istio-cni.yaml
      chart: cni
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.29.2
      helm:
        valueFiles:
          - $values/istio/values/values-istio-ztunnel.yaml
      chart: ztunnel
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: istio
      targetRevision: HEAD
      ref: values
