---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: system
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://charts.longhorn.io/
      targetRevision: 1.11.1
      chart: longhorn
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: longhorn
      targetRevision: HEAD
      ref: values
    - repoURL: https://git.raft.lutris.house/api/packages/the_raft/helm/
      chart: gw-helper
      targetRevision: 0.1.3
      helm:
        valueFiles:
          - $values/longhorn/values/values-gateway.yaml
