---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: system
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      targetRevision: HEAD
      path: metrics-server
      ref: values
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      targetRevision: 3.14.0
      helm:
        valueFiles:
          - $values/metrics-server/values/values-metrics-server.yaml
      chart: metrics-server
