---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data
    - group: '*'
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  sources:
    - repoURL: oci://ghcr.io/prometheus-community/charts/prometheus-node-exporter
      path: .
      targetRevision: 4.53.1
      helm:
        valueFiles:
          - $values/monitoring/values/values-node-exporter.yaml
    - repoURL: oci://ghcr.io/prometheus-community/charts/prometheus-smartctl-exporter
      path: .
      targetRevision: 0.16.0
      helm:
        valueFiles:
          - $values/monitoring/values/values-smartctl-exporter.yaml
    - repoURL: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
      path: .
      targetRevision: 83.4.1
      helm:
        valueFiles:
          - $values/monitoring/values/values-kps.yaml
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: monitoring
      targetRevision: HEAD
      ref: values
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: monitoring/alerts
      targetRevision: HEAD
    - repoURL: https://victoriametrics.github.io/helm-charts/
      targetRevision: 0.11.31
      chart: victoria-logs-single
      helm:
        valueFiles:
          - $values/monitoring/values/values-victorialogs.yaml
    - repoURL: https://victoriametrics.github.io/helm-charts/
      targetRevision: 0.2.15
      chart: victoria-logs-collector
      helm:
        valueFiles:
          - $values/monitoring/values/values-victorialogs-collector.yaml
