---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - kind: Deployment
      group: apps
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  sources:
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: monitoring
      targetRevision: HEAD
      ref: values
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: monitoring/rules
      targetRevision: HEAD
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: monitoring/scrapeconfigs
      targetRevision: HEAD
      directory:
        recurse: true
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-k8s-stack
      targetRevision: 0.89.0
      helm:
        valueFiles:
          - $values/monitoring/values/values-vm-k8s-stack.yaml
    - repoURL: oci://ghcr.io/prometheus-community/charts/prometheus-smartctl-exporter
      path: .
      targetRevision: 0.16.1
      helm:
        valueFiles:
          - $values/monitoring/values/values-smartctl-exporter.yaml
    - repoURL: https://git.raft.lutris.house/api/packages/the_raft/helm/
      chart: gw-helper
      targetRevision: 0.1.4
      helm:
        valueFiles:
          - $values/monitoring/values/values-gateway.yaml
