---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opengist
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: opengist
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://charts.obeone.cloud
      chart: opengist
      targetRevision: 1.1.0
      helm:
        valueFiles:
          - $values/opengist/values/values-opengist.yaml
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: opengist
      targetRevision: HEAD
      ref: values
