---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opengist
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: opengist
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://charts.obeone.cloud
      chart: opengist
      targetRevision: 1.1.0
      helm:
        valuesObject:
          controllers:
            main:
              containers:
                main:
                  env:
                    OG_EXTERNAL_URL: https://gist.raft.lutris.house
                    OG_OIDC_DISCOVERY_URL: https://auth.raft.lutris.house/.well-known/openid-configuration
                    OG_OIDC_GROUP_CLAIM_NAME: groups
                    OG_OIDC_ADMIN_GROUP: cluster_admin
          persistence:
            opengist:
              enabled: true
              storageClass: nfs-ssd-csi
              type: persistentVolumeClaim
              accessMode: ReadWriteOnce
              size: 20Gi

    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: opengist
      targetRevision: HEAD
