---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plik
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: plik
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://root-gg.github.io/plik
      chart: plik
      targetRevision: 1.4.2
      helm:
        valuesObject:
          # persistence:
          #  enabled: true
          #  storageClassName: nfs-disk-csi
          # dbPersistence:
          #  enabled: true
          #  storageClassName: longhorn
          plikd:
            PlikDomain: https://plik.raft.lutris.house
            MaxFileSizeStr: unlimited
            MaxTTLStr: 365d
            FeatureAuthentication: enabled
            FeatureComments: disabled
            # OIDCClientID: Hii0QyEoSpaOEXHnHXMSohsF-IxyO2LeNHmcgpQD0bv0ZSRCtkZUzh02EBJNYbQH524WPGvx
            # OIDCProviderURL: https://auth.raft.lutris.house
            # OIDCProviderName: authelia
