---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plik
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: plik
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://root-gg.github.io/plik
      chart: plik
      targetRevision: 1.4.2
      helm:
        valueFiles:
          - $values/plik/values/values-plik.yaml
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: plik
      targetRevision: HEAD
      ref: values
    - repoURL: https://git.raft.lutris.house/api/packages/the_raft/helm/
      chart: gw-helper
      targetRevision: 0.1.3
      helm:
        valueFiles:
          - $values/plik/values/values-gateway.yaml
