---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: romm
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://valkey.io/valkey-helm/
      targetRevision: 0.9.3
      chart: valkey
      helm:
        valueFiles:
          - $values/romm/values/values-valkey.yaml
    - repoURL: https://git.raft.lutris.house/the_raft/kubernetes.raft
      path: romm
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: romm
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
