---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.18.4
    chart: sealed-secrets
    helm:
      valuesObject:
        metrics:
          serviceMonitor:
            enabled: true
            relabelings:
              - sourceLabels: [__meta_kubernetes_pod_node_name]
                targetLabel: instance
                action: replace
                replacement: $1
          dashboards:
            enabled: true
