---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plik
  namespace: plik
spec:
  dnsNames:
    - plik.raft.lutris.house
  secretName: plik-certificate
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
