---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plik-secret
  namespace: plik
spec:
  encryptedData:
    PLIKD_DEFAULT_ADMIN_PASSWORD: AgAMHX9MTQXzBbUW8gWp9DkI1K/MMkniaQbERVyRWz4EgF9dBSzcwCfDmMond60DSkoxv+ecD9qgprR5QlagjeoCxs5dAPxZgZdkRUG7KvCBMCmZ1J4Rtc545oj5BFbBX2QXqpIcPKNR41m2vx8/EIv6UrbHvH1qim2lelxNWzeVThLyihTcUv5gZ3TlkgR/B9Y+LQXCh/5rJPrypk060Adl7RfGCN9ShpLUA13X7QpIOQ//BJElljHICQfUtaNAjwQ2NrsvoXVcn/9vcRGENE9JLVUDYYFBUR8x+XAEZC26G7FRN4aOoQKKXcPZ4r3SPdVq+vLED88/hvtsuak5wZkzo/kd9y7sg5YcN9cXvvwDOzXWybGR6/4MzpAPTOc6X/9wGkftxJigUZ3vVP2u1ToeoXp1D/XsUgIre+Z/xU6mZ5tmRwP11j0Eoy6CljMpKvWkBY3ikZo/O9f0y7/fBS72/ww+owwKVN5Zj9x8u6/TU6WU/i3ijEaNHimXQfVh1MF6aKhTyfUt0H9DAD3L8myGf65BGRJckb3lZpNqe+uw6SV1UaZfKuE03JVrDyHv62LR3RnC1/79Jsp0/U+6R/ycQlA6CHGPNBJ5muaCT5GCP0bv5eJJcqJ1rzYwlx2trpTxjj/XSGtNGejkOXzG7CK/jdUs8HoPeynfePrrFInWwuVghxq5bldrXtPunc/moYYHIb1Ajtd4QtmilLE=
    PLIKD_OIDC_CLIENT_SECRET: AgAu3s6bpLKY+FX/8BXHcv3OPBVmZMvfeJpTjbfZK+rbxub/rwkx33z91h8vQ7XzcW2sNWQVwo4mctb4fD8EnLblXU6iBpGb7XEYcscHqHmfqUAF9FYQNpEaTH9l8nonsMX+Rvn4X1h9DjOTJ8c09O8VHfwtZHsr0+qWc8Dm5daX+02z+S9JdpVl3KEQUFycRmt01toMveembh8IFbK2snoxNkEyB0CwGUZBHQcTSE318JfLrObn8Zd1CELlBN30sUXXPBzL3xqxE3OWRurokUjKvKLFtOtDIwGjMKQ3NxkqXml2UHL/IzNZ1V7bSWteTx5rAN4+hGrGWCx1FMDxR2UawUQjvENdVtg7hggJ0Dr9GlqAIk4bAE7lG6E0zbr+pm5mUAd38kud8d9wROt7pmywh5YlkDlJgdixJfKS2CUCWmiIeWykvtGQxER5NWqtpdXj6OUZ4cXpscnVPNSqSfh7c/jC18fL3SP9mhlhX4iNr5Y4XCojeo8yNi5bHeLE4agegpdNezsoHzNTexKfuQDCNJEI5kgcaEFGdCwyoyFCunglyWh6hJpxK1HzVTwTz+xshRiacYi3cirIweMCCJE3rN3V6iaNGOirHLg4ErF8vop+eKBaefaACDlWL4HR9UgIlfghp+gFlnu80wxAiTXYmt5iYEWEp9qycZBzcSVYz1xk/lcKae7mUus9FdQMxWBVWN14qpy5R3V5LQgytO0uHq2KCR9x9WEKBV78/3XnsDAH1/GW3jcgZ6cldZe2QLQzbH7pAJxpOijjv5cVqXV6l14067WP9cU=
  template:
    metadata:
      name: plik-secret
      namespace: plik
    type: Opaque
