gateways:
  - name: monitoring
    hostnames:
      - grafana.raft.lutris.house
    listeners:
      - name: https
        port: 443
        protocol: HTTPS
        routes:
          - name: grafana
            service: monitoring-grafana
            port: 80
            hostnames:
              - grafana.raft.lutris.house
