---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-cm
  namespace: dashy
data:
  conf.yml: |
    ---
    # Page meta info, like heading, footer text and nav links
    pageInfo:
      title: The Raft Intranet
      description: A world of possibilities!
      navLinks:
        - title: Config
          path: https://git.raft.lutris.house/the_raft/kubernetes.raft/src/branch/main/dashy
        - title: Documentation
          path: https://dashy.to/docs

    # Optional app settings and configuration
    appConfig:
      theme: colorful
      webSearch:
        searchEngine: google

    # Main content - An array of sections, each containing an array of items
    sections:
      - name: Authentication
        icon: fas fa-user-lock
        items:
          - title: Authelia
            description: OIDC Login and password management
            icon: https://www.authelia.com/favicon.ico
            url: https://auth.raft.lutris.house/
            target: newtab
      - name: Development
        icon: fa-solid fa-file-code
        items:
          - title: Forgejo
            description: Fork this site
            icon: https://forgejo.org/favicon.ico
            url: https://git.raft.lutris.house/
          - title: Livecodes
            description: Livecodes
            url: https://livecodes.raft.lutris.house/
            icon: https://livecodes.io/favicon.ico
      - name: Media
        icon: fa-solid fa-photo-film
        items:
          - title: RomM
            description: Vidja Gaems!
            url: https://romm.raft.lutris.house/
            icon: https://romm.app/favicon.ico
          - title: Immich
            description: Photos!
            url: https://immich.raft.lutris.house/
            icon: https://immich.app/favicon.ico
      - name: Productivity
        icon: fa-solid fa-file-lines
        items:
          - title: Cryptpad
            description: Docs n shit
            url: https://cryptpad.raft.lutris.house/
            icon: https://cryptpad.fr/favicon.ico
          - title: Plik
            description: File drop/share
            url: https://plik.raft.lutris.house/
            icon: fa-solid fa-download
      - name: idk it's the cat's stuff
        icon: fas fa-cat
        items:
          - title: Gwams
            description: Gwams
            url: https://gwams.raft.lutris.house/
            icon: fa-solid fa-child-combatant
      - name: Monitoring
        icon: fas fa-chart-line
        items:
          - title: Grafana
            description: The Raft system monitoring
            url: https://grafana.raft.lutris.house/
            icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Grafana_icon.svg/500px-Grafana_icon.svg.png
          - title: Prometheus
            description: Prometheus rules and targets
            url: https://prometheus.raft.lutris.house/
            icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/500px-Prometheus_software_logo.svg.png
          - title: Alertmanager
            description: Alertmanager alerts and silences
            url: https://alertmanager.raft.lutris.house/
            icon: fas fa-bell
      - name: System Administration
        icon: fa-solid fa-users-gear
        items:
          - title: ArgoCD
            description: ArgoCD deployment system
            url: https://argocd.raft.lutris.house/
            icon: https://icon.icepanel.io/Technology/svg/Argo-CD.svg
          - title: LLDAP Frontend
            description: User management
            url: https://ldap.raft.lutris.house/
            icon: fa-solid fa-users-viewfinder
          - title: PiHole
            description: PiHole Frontend
            url: https://pihole.raft.lutris.house/
            icon: https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png
