---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgDHgYcmX6FenXi3J5kHHOlS4n4biS5tI8hkw210sSY254+aaSGqUcKK0gZlgaDysoJmp7md1azuw7CMC+xupGserd1H7+k+YhEUGCcJcAgi+JsjAJ8iwLvuxBg0KwxJWz5WwHG/noC/2WZ86eSIomOiHajBhvo+XBT11yR2PNL7ZX5JnKmZhiMFnfcvsBP7gQ9Plk8dXV5wDxH5F7OBxK/F0/vZP044xP7PdcvcaT6gcogm25P082jkZ1rNUza9/I7DBw3In2TzMrHuIAeKWJklYETw3x2k86aSQkdBOWafY+jl08CdlaPqSKBgAhloeqLN8Ctn6BMkYfogLb51qaurf613+knjolp0YTUvIwMV9lXAwEPjkinspHE8wMatYB5+C6XaysaeMxpzePZ8ByTGOHjpnPNL+D4lQPNLTzTuf9ZIER7/geLyQzlZ6ud9igW5G6azD0MMI9uiKCzBxdmfy3co/cDACwM+Ry1qgTi+gxhv7Y+anATf4aEC0nGmxE0QfUgVzgNGFLZyECBHXTccfqmwHXVKfqVLEulj0ZkrNVK8xrsn/fdFxBTYpieyM/OVcnebWlhx8kG1sMrWFdTkhW+a+d2vi8OwHwLUumE93nYSWa1M5t/mlWKqs03NcDvVDVmfFxHkE1KjJ5eUZymXwzd4vIgEqjC4WX6/DvnsncUMq4VJPmCpE/8G3TeDaPKleqbZvZ44hRNx64Zq+6gA/wTDbs0c2Q/prsF11hI2elV4ptNh0Gn2Flz/wL0lzOBHvD8uKw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
