---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    secret: AgAG0q15wal9XPQB1puBLiUq0Mb1+o/KEcba6Ril9f8+FDOw0N6HKwdrgAHZT3RpdkADlDwJyyhTZwjvGs//KLSfPC3+yZYm32qSNM0tU4DIV8V1qYtsB7cot6U1eORIxEPkCIbubxu+OI7Q1H61mn+b8QenW7tNYOoFWqkhXD4ZckOiPD3dM6TspwZEOu3K3S9ATtEgUKLmR9yOli0U20qCZMeCP60vtaqSBxTydN2YkmCYDbRuyiaHTtbrV3SiBBTltPilKziYVxh5DMAyWSGTneNvuSIu8/9+rMx20bTQQRZAAq6eoJwcRfdzY624BvfAE22YZOZydsIzclsEh++chZM1pvUjFbHtsO25KT7m7Z+khYV6kiJ+Ce7thWC6PTvrXOOVOm4Llhxqt/Mc4u4EnqoRkdzSGLgd1ATou9cXN8WFYnqcyUvy+KkoR+rs2cgqVEBUYrlGNCzbfhVPdOzHv0ats6UpcGMa090qYV3rQyLvdhDJI/LdPLtlMUXVfn4Va1TO/C6FS67nvKSrCLl2SAzm30ry+h+oua+HHk0OrkJ5Pb/wmavDxU/YR96Ojmtt0DZWNeyBkBnspxcRdNwfc8mDrnPUdwesUJNJsWLsXSndH9ZaMghSsCsp44YJ+rtYhsWKrT5frvFg9pr00E+nUnBTnE4CiaqVGv7sE4jUxjz2raAF0ew5KCJUw3BJYpISxtRuap45V0bjARoecpRfWmWTazOyibihUn8ftaMISXNd90OgtAFXM5tLDw==
  template:
    metadata:
      name: external-dns
      namespace: external-dns
    type: Opaque
