---
rbac:
  create: true

sources:
  - service
  - gateway-httproute
  - gateway-grpcroute
  - gateway-tcproute
  - gateway-udproute
  - node

serviceMonitor:
  enabled: false

registry: txt

txtOwnerId: k8s

txtPrefix: external-dns-

policy: sync

provider:
  name: cloudflare

extraArgs:
  - --no-exclude-unschedulable
  - --expose-internal-ipv6

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: apiKey
