---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cainjector-monitor
  namespace: cert-manager
spec:
  selector:
    matchLabels:
      app: cainjector
  endpoints:
    - port: http-metrics
