---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBLJzUGbfAFyKM4gDzt9NwQwsN6PHM2D1XXhllq4ChfA2TY61id2Z4d5iH3W5DO0EMqlk9hTGuKPrJLtdGSFwNF9oiTZVZJ4kMnc/iPXjTGqxEWy8AWRNgpJSFV4rhsZmkm2ram8eozZ+MNwTCGFOjegWxvEGtxuXxKiOND5MHVg5r2B9HaEgxoSa7NM8k8woomqhXtu4O0x52k2PLKq6mnInnbHcEAtJuNO13ykDpGJF32o/UZ+r99Uvv4poTG6nIGceER/cYKoNLqCj50BUBwfvnFJjjnUVYwilea2YECnrLcfTRLu2Tv9nzZx/up0JFiZC12kIzcpKDhUN7F4GOkG7wKdUYtcoDm+L1bqi7N4Y7cZAsYDGlgi52BSjmyBHtN2aKncAg7iNJpDJZMVtYkcBifjYdPMueSV5+3B8KJ2s5bpTDa7C6I1zFINmvJN//hYBDtN8LGoNHprauJw85OsH0uGgmyDCc8c6wVZXS1Fqa9KWKq3eiWgHXgzXLSksfQ4JI+OSEQpklwqnM987ReIqhac2zg+wqNzJABfmerW3ZvSv5L4mqtM+k3Ku1iZuL5Ja/425sO3LVEKj1NVnlszUtWsJY634yu/fYcPRlwQs/EEUVGKuGyltEji/t0ZwVW3IGCfkok2WSDp0S0Ij8PJ8MDz9dyJp12O2gwHi3QzhYM4KSXTwPx9XR/JlHlOvqRpvRbbvaRizOVm7Ijiuop2sxdC282F7uY5KFjwK3R/lEPUlr4uQwxxw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
