---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCAss9o3ikh3w0cONAe2SRgqxFvRy4lVKuJtxN8/RCWIcvMS46UDeLvspcrEQ2M7kUBtNcNj2A3m8TIb09aUPpZO53OYDSNjgXCvUvtjuPRH8vyUf+ikiYcJBRMDZawXGm1bhc/vhtnkDJNo+/4pHi79r/Adt4A32ZH5OVrQYqzhk9RKdSbK+nARVErXjjdtekXh9rm+S3TVt/ACY15A+rWIMU++Xl24cmmKEgml6LyAy/Hig0qGXIrvP9nuTGfAVhM7ODImTjKIFqT09vqFt33j3Dr8Zw0eojYNpGK8yZPmS4tAflGvEJrwDacxVBD1DVrUD9kACLKwqik5es7Lqai8478NYnEU4OdSwa9f2kaGNTEQqkFPiFrTW/n7CpLUwj2IpbJorOCImMrT8nM57GHRdqQ7U58lBNOzqK3lKUtGYKRgtw1nuXPHwfn//YWXUnT6YDfAapE0XZ3C9bsbbgNThC7QIvr5LvbFC17nN6zwPiSYgHcGYkT1zCSdydLnkZi+c7VzMqM4aWIN3Pr4HMAp9Am9fgwmnhH2xlIi69HW0NyRQV5veneXsmGhWleuWNN/4XVaK/qlR3IXeYwWE1hAHkFFQW/+HHTxAQjpF4U/r2RrsijyNvKcI30KcmE3orTZqcsiaLQHhhRvCynY9FUj0cChnMqb2f1bUgrvZWMGp4zFGAhlM+o9RmPygIY00wNdxbCrwqQT0iL9qa+waV9bWaBmA7/5IYr70Dw9ebIFbJNajl0zI9PkA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
