---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgCbEKtZVPYm3OKPL+cpoM6WswHS3tgkPuKkQiv30oJwldKI9chwZUh/hc+yp/mANeWJdDjMaelU02j/3F5yNqFih0gfFLljNbhbWlEhUQaNGBkGtauFoBQjxhmrwecretnPGpARmidSx7kCEolWsZmAaI5F5kgnl7aoui20fKMCxU1mCk1ljkx7pvaavOAgyN1IeTVmwbyVcDCbLEa7OeQseWcKNUhuogLRb3IPYumAcrBPpcbTsSSyBsMLpE7dLkuNmigr/v8q0++F4VG3X8uiEseyGcKQIO7Y5+nm2VLS/xeeHHwtFkwBKnat/mxXH4kXzFrXOjYLz/T44wrTcgESGQ030CDQ2d+YpOfktRikU941JHTg2ULVduUOalJ1rCseuTKxQnYNfAvuEsfsRlFfptcm9uPM3xjP9jFGus/AxnmsVKyQhW/KgRPJR/3yuWTt/x950Cpg3h4Co34aOdjGjnyUc+KQ6BbigZRHp2ZGzxQZEjU6lEX/XL84IOpo0Z6I8/hO1irhjoOddp70BYju1nA/aiAgiSMN7GawAoWMA5KKRgNG12mMZGBGvCm1Eps+Gwng2i+zaLSdQ7sXmNy21rMyaKsg+tuUpv2aPoYeLu2/Zam+0MM0wVE9XFCia5JShukU/8EVPvWRTuvZx5cs/oDQHsa2kk5BlYyYhsVDtBE5iJ1UjfpZR+B1EzaUmJ6mUCJNR+rtulHO0/cuitEuxrZm4LSsfaEnHiPtKCDEh3f1VOgC
  template:
    metadata:
      name: cloudflare-api-key
      namespace: cert-manager
    type: Opaque
