---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAEQBa4LyrzX58Nasp8U0QzLF0uyYxdyi/9sC6KQeYuuYqKWEq1yjtHmQ17DHyCFp9YRZH9H+3vcw/gWXMaQxUv67iewSPFSPJQyGavnG5h3E6nv2CyJ88EAkivbpPMJAPIXQWLTYr2E+I4Y9iqSt/kCGA10VgXUcTCeqFy0zFQx15xAqPvYmSohyTbmeThy5AaISmj4ld1FMcC80Ayga7yvM4VI0002MHeCce/MQC/D9JfWIrS6E6gTkA59lG2Ywv2alFzdoHj3ub32e2MWJiJLxT4mBTHmE0ZTqOXnOBbVVfSOZi3/nCdLN3yl3uVq9Xd9BTD+Fpov0tw5qlK5HuK2Bt9OF8TBTUZyPycn8ejzZJFA/WkcK0rMrqxoaf9gt7sTqEpWYXA/b4pqDiPNXK9FC+ZOBfbC0pa/Osdjqgt0/vib/4t92REhLuUXGJAlvV6T0LL+ZYyetw7jF/f421vz53wg+N/y9uofVaJDgAXed7mh2K3JjSL7eMBY1XzSISNaayhpkw8nBNyHo1FBXE0bPQBCfyGaLT5FY4kruR7wzPBxQ61U6rkfeKkUzEnyuRukIZKMfZgevwtCveNKaIifUz8M8cm2ZILjF7j5Krxnu02FYQSo7S01nAzgoTXMyspS8efRAGTfVXB0aSYzDeyzWx22NpqvalVqjdyCNEKFML0KyLWqE0QjrWZdI/BpotQsB59qqhvBINu0xcIDefCWZNd0vu/L097swN3f0peNA+F43WtLfHjSngecLOBlisfvgD33g==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
