---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: alice@tuxnami.org
    privateKeySecretRef:
      name: letsencrypt-dns01-api-key
    solvers:
      - dns01:
          rfc2136:
            nameserver: 172.16.62.40:53
            tsigKeyName: zone_update.key
            tsigAlgorithm: HMACSHA256
            tsigSecretSecretRef:
              name: tsig-secret
              key: tsig-secret-key
