---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsig-secret
  namespace: cert-manager
spec:
  encryptedData:
    tsig-secret-key: AgBSFrokgLAfk4YyAJBUQ5Rz447d+hkaDVaAeLE1AdIQZ+lNqSgcYMYjXqyIj/3MFY9Pk2aAxxv1eajR0kOiCaWyu2uaCRVAso3Uu89UsPyejBvy+9podisOtYrZf7CeiIEjf06sK1TY3M5PCMsWmMU99k/fDajf5bKdYfdjUMDoGPZqG0tB+mAj5alUtZt07iFR4fyeO3z0Y9/3EpVDlD0UsgbKQqrmhWfyWx6kluEwWrMzdf7if9Bk7xUWWmDLCDstEfu0pVcoVGCrKilpd+Ey53R+XueeVQnyAgI6AFCZ7vpMSJ78JCj30TxxGIoSNeGczbrsooudmLIEXuy9O0m7AsU2ehl30UdnFKuu+T+AUwpnEN7TLnkJfm9Ph0QZ2h6B/OXyfDUyHpFHbbGJl/xghXYSZa0gzOGp/mRQpE2pPvdiqecv4/unIkfg/pTzt9eS9s5z4mfCsypLUuD4LSpsUhQTH1P2CCc4l8S/JeCTI0guiwQZAgrUxyGIJHKRYIqwUEXi/JEN1sjhAe2BbviRLfE+572l7sZ1ZagQgHUkAtIxnXUQm8Bi6V/tUCiJDm/BVM4A9iqpuor4erv88AyGoGxJ8nGv810nJgV3oSgaQfOyddhCAEWPV19Mva+9GV0d68O34tDPCXBfKdM/Xzyzv80bZB9g25hzHX9Q5RZLkyEuo6xjvJZYEFsSNuvjE6YLxa/BZE3986/KrBpvYfrHMyzfvpQ+zBY8VxCsiIT58eWReqziey6JeVV8LQ==
  template:
    metadata:
      name: tsig-secret
      namespace: cert-manager
    type: Opaque
