---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webhook-monitor
  namespace: cert-manager
spec:
  selector:
    matchLabels:
      app: webhook
  endpoints:
    - port: metrics
