---
global:
  storageClass: nfs-ssd-csi
clusterDomain: polycule.raft.lutris.house
securityContext:
  capabilities:
    add: ["SYS_CHROOT"]
gitea:
  metrics:
    enabled: true
  config:
    server:
      ROOT_URL: https://git.raft.lutris.house/
      DOMAIN: git.raft.lutris.house
      SSH_DOMAIN: git.raft.lutris.house
      ENABLE_PPROF: true
    database:
      DB_TYPE: postgres
      HOST: "forgejodb-rw:5432"
      USER: forgejo
      NAME: forgejo
    mailer:
      ENABLED: true
      PROTOCOL: smtps
      SMTP_ADDR: smtp.gmail.com
      SMTP_PORT: 465
      USER: alicelutris@gmail.com
      FROM: noreply@git.raft.lutris.house
  additionalConfigFromEnvs:
    - name: FORGEJO__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: forgejo-pg-user
          key: password
    - name: FORGEJO__MAILER__PASSWD
      valueFrom:
        secretKeyRef:
          name: forgejo-smtp-secret
          key: PASSWD
persistence:
  size: 400Gi
