# -- Toggle to allow this last version of helm-chart
knownLastVersion: true

runner:
  config:
    create: true
    name: runner-test
    token: JPdF4zFAUNdAJXuP3pvWM506QrUVNrlUgXKeOH8uLXz
    instance: https://git.raft.lutris.house
    file:
      runner:
        labels:
          - self-hosted
          - linux
          - amd64
          - docker
          - ubuntu-latest
        envs:
          DOCKER_HOST: "tcp://localhost:2376"
        #  DOCKER_TLS_VERIFY: "0"
      container:
        privileged: true
        valid_volumes:
          - "**"

volumes:
  - name: docker-data
    emptyDir: {}
  - name: docker-config
    configMap:
      name: runner-docker-daemon

volumeMounts:
  - name: docker-data
    mountPath: /var/lib/docker
  - name: docker-config
    mountPath: /etc/docker/daemon.json
    subPath: daemon.json
